name: 'Publish wiki'

on:
  workflow_run:
    branches: [main]
    workflows: ["Build And Test"]
    types:
      - completed

concurrency:
  group: publish-wiki
  cancel-in-progress: true

permissions:
  contents: write
  actions: read

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
        - name: 'Checkout repo'
          uses: actions/checkout@v3
          with:
            submodules: recursive

        - name: 'Download build artifacts'
          uses: dawidd6/action-download-artifact@v2
          with:
            name: build-artifact
            run_id: ${{ github.event.workflow_run.id }}
            workflow_conclusion: success


        - uses: actions/setup-node@v3 # setup node
          with:
            node-version: 18

        - run: npm ci # install packages
        - run: npx typedoc # produce wiki

        - uses: Andrew-Chen-Wang/github-wiki-action@v4 # publish wiki
