name: 'Release'

on:
  workflow_run:
    branches: [main]
    workflows: ["Build And Test"]
    types:
      - completed

concurrency:
  group: release
  cancel-in-progress: true

permissions:
  contents: write
  actions: read

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
        - uses: actions/checkout@v3 # checkout the repo
          with:
            submodules: recursive

        - uses: dawidd6/action-download-artifact@v2 # download artifacts
          with:
            name: build-artifact
            run_id: ${{ github.event.workflow_run.id }}
            workflow_conclusion: success


        - uses: actions/setup-node@v3 # setup node
          with:
            node-version: 18

        - run: npm ci # install packages
        - run: npx semantic-release --dry-run # release

